version: 32.0.2.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 1
init:
- cmd: git config --global core.autocrlf true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: srcrepair.sln
  parallel: true
  verbosity: normal
after_build:
- cmd: >-
    set CI_DIR=%APPVEYOR_BUILD_FOLDER%\srcrepair\bin\%CONFIGURATION%

    set CI_HASH=%APPVEYOR_REPO_COMMIT:~0,7%

    7z a snapshot_%CI_HASH%.7z %CI_DIR%\*

    "%ProgramFiles(x86)%\Inno Setup 5\ISCC.exe" %CI_DIR%\inno\srcrepair.iss

    move "%CI_DIR%\inno\Output\*.exe" .
test: off
artifacts:
- path: snapshot_*.7z
  name: snapshot
- path: snapshot_*.exe
  name: innosetup
