version: 36.0.2.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
configuration: Release
platform: Any CPU
clone_depth: 1
init:
- cmd: git config --global core.autocrlf true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: srcrepair.sln
  parallel: true
  verbosity: normal
after_build:
- cmd: >-
    set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%

    set CI_DIR=%APPVEYOR_BUILD_FOLDER%\srcrepair\bin\%CONFIGURATION%

    set CI_HASH=%APPVEYOR_REPO_COMMIT:~0,7%

    pip3 install "sphinx==1.8.2"

    call docs\help\make.cmd htmlhelp

    "%ProgramFiles(x86)%\HTML Help Workshop\hhc.exe" docs\help\build\htmlhelp\srcrepair_en.hhp && exit /b 1 || exit /b 0

    mkdir %CI_DIR%\help

    move docs\help\build\htmlhelp\srcrepair_en.chm %CI_DIR%\help\srcrepair_en.chm

    7z a -m0=LZMA2 -mx9 -t7z -x!*.ico -x!DotNetZip.xml -x!NLog.xml packaging\results\snapshot_%CI_HASH%.7z %CI_DIR%\*

    "%ProgramFiles(x86)%\Inno Setup 6\ISCC.exe" packaging\inno\srcrepair.iss
test: off
artifacts:
- path: packaging\results\snapshot_*.7z
  name: snapshot
- path: packaging\results\snapshot_*.exe
  name: innosetup
