version: 31.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 1
init:
- cmd: git config --global core.autocrlf true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: srcrepair.sln
  parallel: true
  verbosity: normal
after_build:
- cmd: >-
    set CHASH=%APPVEYOR_REPO_COMMIT:~0,7%

    7z a snapshot_%CHASH%.7z %APPVEYOR_BUILD_FOLDER%\srcrepair\bin\%CONFIGURATION%\*

    findstr /V "_RELEASE" inno\srcrepair.iss > inno\srcrepair.iss

    "%ProgramFiles(x86)%\Inno Setup 5\ISCC.exe" inno\srcrepair.iss
test: off
artifacts:
- path: snapshot_*.7z
  name: snapshot
- path: snapshot_*.exe
  name: innosetup
