#
# SPDX-FileCopyrightText: 2011-2025 EasyCoding Team
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

name: Linux CI

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    name: Build project using Mono
    runs-on: ubuntu-22.04
    steps:
    - name: Fetching sources
      uses: actions/checkout@v4
    - name: Updating apt package metadata
      run: |
        sudo apt-get update
    - name: Installing NuGet package manager
      run: |
        sudo apt-get -y install nuget
    - name: Restoring dependencies with NuGet
      run: |
        nuget restore srcrepair.sln
    - name: Building project with MSBuild
      run: |
        msbuild /p:Configuration=Release srcrepair.sln
