name: Linux CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install mono and nuget
      run: |
        sudo apt-get update
        sudo apt-get -y install mono-devel ca-certificates-mono nuget
    - name: Restore nuget dependencies
      run: nuget restore srcrepair.sln
    - name: Build project
      run: msbuild /p:Configuration=Release srcrepair.sln
