#
# SPDX-FileCopyrightText: 2011-2024 EasyCoding Team
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

name: Windows CI

on:
  push:
    branches:
    - 'master'
    - 'legacy'
  pull_request:
    branches:
    - 'master'
    - 'legacy'

jobs:
  build:
    name: Build project using .NET Framework
    runs-on: windows-latest
    steps:
    - name: Fetching sources
      uses: actions/checkout@v4
    - name: Configuring MSBuild service
      uses: microsoft/setup-msbuild@v1.3
    - name: Restoring dependencies with NuGet
      run: |
        nuget restore srcrepair.sln
    - name: Building project with MSBuild
      run: |
        msbuild /p:Configuration=Release srcrepair.sln
